export const jetsoftCopy = {
  'pt-BR': {
    pageTitle: 'Jetsoft — Inovação é a chave',
    metaDescription: 'Jetsoft — tecnologia aplicada para transformar desafios reais em operações mais eficientes.',
    languageGroup: 'Selecionar idioma',
    languagePortuguese: 'Português (Brasil)',
    languageEnglish: 'Inglês (Estados Unidos)',
    logoHome: 'Jetsoft — início',
    navLabel: 'Navegação principal',
    nav: ['Sobre nós', 'O que fazemos', 'Nosso portfólio', 'Blog'],
    contact: 'Contato',
    menuOpen: 'Abrir menu',
    menuClose: 'Fechar menu',
    hero: [
      {
        eyebrow: 'JetERP',
        title: 'Transformando sonhos em realidade com tecnologia inovadora.',
        copy: 'Gestão completa para transformar a complexidade do seu negócio em decisões mais simples.',
        action: 'Conheça as soluções',
      },
      {
        eyebrow: 'JetBPM',
        title: 'Não perca tempo com processos ultrapassados.',
        copy: 'Mapeie, melhore e automatize as rotinas que fazem sua empresa avançar.',
        action: 'Conheça nosso processo',
      },
      {
        eyebrow: 'Jetsoft',
        title: 'Modernize sua gestão e aumente seus resultados.',
        copy: 'Tecnologia aplicada ao seu contexto, com proximidade, método e visão de longo prazo.',
        action: 'Fale com a Jetsoft',
      },
    ],
    heroBottom: 'Estamos aqui para simplificar sua jornada.',
    pauseRotation: 'Pausar rotação dos destaques',
    resumeRotation: 'Retomar rotação dos destaques',
    pause: 'Pausar',
    resume: 'Retomar',
    heroDots: 'Escolher destaque',
    showHero: 'Mostrar destaque {number}: {name}',
    carousel: 'carrossel',
    pillarsLabel: 'Soluções Jetsoft',
    pillars: ['Gestão total do seu negócio', 'Mapeamento, melhoria e automação de processos', 'Plataforma de e-commerce'],
    aboutTitle: ['Somos ', 'especialistas', ' em desenvolvimento de software.'],
    aboutCopy: 'Ajudamos empresas a transformar desafios reais em operações mais eficientes, com tecnologia que evolui junto com o negócio.',
    aboutAction: 'Conheça nosso método',
    aboutImageAlt: 'Equipe e tecnologia Jetsoft',
    aboutImageCaption: 'Tecnologia com visão humana',
    expertiseLabel: 'Diferenciais Jetsoft',
    expertise: [
      {
        title: 'Produto de qualidade',
        copy: 'Atualização constante com as melhores práticas do seu segmento, garantindo um produto que atende suas demandas em tempo real.',
      },
      {
        title: 'Solução de problemas',
        copy: 'Customização de acordo com suas necessidades, utilizando tecnologia de alta performance para sua gestão.',
      },
      {
        title: 'Atendimento humanizado',
        copy: 'Atendimento rápido e personalizado para garantir respostas claras e decisões mais seguras.',
      },
    ],
    stats: {
      retention: ['de clientes', 'fidelizados!'],
      items: [
        { title: 'Custos reduzidos', copy: 'Invista um valor justo e otimize o tempo com um dos mais completos softwares de gestão do mercado.' },
        { title: 'Otimização de processos', copy: 'Interfaces claras e intuitivas facilitam a adaptação da equipe ao software.' },
        { title: 'Software completo', copy: 'Interoperabilidade para integrar plataformas de e-commerce e os sistemas que sua empresa já utiliza.' },
      ],
    },
    cases: {
      kicker: 'Casos de sucesso',
      title: 'Parceiros que transformaram seus resultados.',
      previous: 'Case anterior',
      next: 'Próximo case',
      action: 'Fale sobre este case',
      select: 'Escolher case',
      descriptions: [
        'A parceria com a Alemmar começou com a modernização da operação comercial e evoluiu para assistência técnica, importação, financeiro e estoque — uma transformação contínua, construída lado a lado.',
        'Há mais de uma década, contribuímos com sistemas de missão crítica para a Secretaria da Fazenda e Planejamento, apoiando mais de 450 mil usuários em processos estratégicos.',
        'Mapeamento de processos, integração e novos projetos de software ajudaram a Guima Conseco a avançar em áreas essenciais como RH, compras, finanças e engenharia.',
        'Uma relação de mais de 25 anos que conecta JetERP, e-commerce e operação omnichannel para sustentar crescimento consistente e novas oportunidades.',
      ],
    },
    trust: {
      kicker: 'Confiança construída',
      title: 'Parceiros que confiaram na gente.',
      copyBefore: 'Durante esses anos atendemos ',
      copyMetric: '+530 empresas',
      copyAfter: ' de diversos segmentos.',
      logos: 'Empresas parceiras',
    },
    process: {
      kicker: 'Nosso método',
      title: 'Como inovamos para encontrar soluções.',
      intro: 'Um ciclo de trabalho transparente, colaborativo e orientado a resultados.',
      steps: [
        { title: 'Descoberta', copy: 'Primeira fase para decidir quais recursos priorizar ou criar durante o processo de produção.' },
        { title: 'Refinamento', copy: 'Deixamos cada item mais claro, tornando a tarefa simples de entender e executar.' },
        { title: 'Desenvolvimento', copy: 'Uma equipe focada em um objetivo que reflete o valor real a ser entregue no prazo.' },
        { title: 'Inspeção e adaptação', copy: 'Revisamos o que foi construído e determinamos as adaptações que vêm a seguir.' },
        { title: 'Feedback', copy: 'Ouvimos as pessoas certas para apontar a direção e confirmar se o resultado foi alcançado.' },
      ],
      contact: 'Fale com um especialista',
    },
    solutions: {
      kicker: 'Soluções',
      title: 'Transforme necessidades em realidade.',
      intro: 'Descubra como a Jetsoft pode impulsionar o seu negócio.',
      descriptions: [
        'Gestão completa e integrada para o seu negócio de ponta a ponta.',
        'Aumente a visibilidade da sua marca com soluções de marketing digital.',
        'Venda mais online com uma plataforma integrada aos principais marketplaces.',
        'Desenvolvimento de software sob medida: aplicativos, sistemas web e soluções inovadoras.',
        'Invista no seu time com treinamentos, capacitação e consultoria.',
        'Otimize seus resultados com mapeamento, melhoria e automação de processos.',
      ],
      action: 'Converse sobre {name}',
    },
    articles: {
      kicker: 'Conteúdos',
      title: 'Atualize-se sobre tecnologia e negócios.',
      action: 'Converse sobre este tema',
      items: [
        { date: '28.05.2024', title: 'ERP online é tão seguro quanto um ERP tradicional?', aria: 'Converse com a Jetsoft sobre ERP online' },
        { date: '22.05.2024', title: '“Hello, World”: a primeira mensagem da programação', aria: 'Converse com a Jetsoft sobre programação' },
        { date: '22.05.2024', title: 'As vantagens de adotar uma ferramenta low-code', aria: 'Converse com a Jetsoft sobre low-code' },
      ],
    },
    footer: {
      brand: 'A Jetsoft é uma empresa brasileira, nascida do desejo de ver sonhos se transformando em realidade.',
      usefulLinks: 'Links úteis',
      home: 'Início',
      contactInfo: 'Informações de contato',
      footerLead: 'Queremos ouvir sobre seus desafios.',
      footerAction: 'Entre em contato para encontrar soluções',
      rights: 'Todos os direitos reservados.',
      backToTop: 'Voltar ao topo',
    },
    social: { linkedin: 'LinkedIn', instagram: 'Instagram', facebook: 'Facebook' },
    whatsapp: 'Fale com a Jetsoft pelo WhatsApp',
  },
  'en-US': {
    pageTitle: 'Jetsoft — Innovation is the key',
    metaDescription: 'Jetsoft — technology that turns real challenges into more efficient operations.',
    languageGroup: 'Select language',
    languagePortuguese: 'Portuguese (Brazil)',
    languageEnglish: 'English (United States)',
    logoHome: 'Jetsoft — home',
    navLabel: 'Main navigation',
    nav: ['About us', 'What we do', 'Our work', 'Blog'],
    contact: 'Contact',
    menuOpen: 'Open menu',
    menuClose: 'Close menu',
    hero: [
      {
        eyebrow: 'JetERP',
        title: 'Turning your ambitions into reality with innovative technology.',
        copy: 'End-to-end management that turns business complexity into simpler decisions.',
        action: 'Explore our solutions',
      },
      {
        eyebrow: 'JetBPM',
        title: 'Stop losing time to outdated processes.',
        copy: 'Map, improve, and automate the workflows that move your business forward.',
        action: 'Explore our process',
      },
      {
        eyebrow: 'Jetsoft',
        title: 'Modernize your operations and grow your results.',
        copy: 'Technology tailored to your context, with close collaboration, proven methods, and a long-term vision.',
        action: 'Talk to Jetsoft',
      },
    ],
    heroBottom: 'We are here to make your journey simpler.',
    pauseRotation: 'Pause featured slides',
    resumeRotation: 'Resume featured slides',
    pause: 'Pause',
    resume: 'Resume',
    heroDots: 'Choose a featured slide',
    showHero: 'Show featured slide {number}: {name}',
    carousel: 'carousel',
    pillarsLabel: 'Jetsoft solutions',
    pillars: ['End-to-end business management', 'Process mapping, improvement, and automation', 'E-commerce platform'],
    aboutTitle: ['We are ', 'software development', ' specialists.'],
    aboutCopy: 'We help companies turn real challenges into more efficient operations, with technology that evolves alongside their business.',
    aboutAction: 'Discover our approach',
    aboutImageAlt: 'Jetsoft team and technology',
    aboutImageCaption: 'Technology with a human perspective',
    expertiseLabel: 'The Jetsoft difference',
    expertise: [
      {
        title: 'Quality products',
        copy: 'Continuous updates based on the best practices in your industry, delivering a product that meets your needs in real time.',
      },
      {
        title: 'Problem solving',
        copy: 'Solutions tailored to your needs, using high-performance technology to support your operations.',
      },
      {
        title: 'Personal support',
        copy: 'Fast, personalized support for clear answers and more confident decisions.',
      },
    ],
    stats: {
      retention: ['customer', 'retention!'],
      items: [
        { title: 'Lower costs', copy: 'Invest fairly and save time with one of the market’s most comprehensive management software platforms.' },
        { title: 'Streamlined processes', copy: 'Clear, intuitive interfaces make it easier for your team to adopt the software.' },
        { title: 'Complete software', copy: 'Connect e-commerce platforms with the systems your company already uses.' },
      ],
    },
    cases: {
      kicker: 'Customer stories',
      title: 'Partners who transformed their results.',
      previous: 'Previous story',
      next: 'Next story',
      action: 'Explore this story',
      select: 'Choose a customer story',
      descriptions: [
        'Our partnership with Alemmar began by modernizing its sales operations and grew to include technical support, imports, finance, and inventory—a continuous transformation built side by side.',
        'For more than a decade, we have contributed mission-critical systems for the São Paulo State Department of Finance and Planning, supporting more than 450,000 users in strategic workflows.',
        'Process mapping, integrations, and new software projects have helped Guima Conseco move forward in essential areas such as HR, procurement, finance, and engineering.',
        'A partnership spanning more than 25 years, connecting JetERP, e-commerce, and omnichannel operations to support steady growth and new opportunities.',
      ],
    },
    trust: {
      kicker: 'Built on trust',
      title: 'Partners who put their trust in us.',
      copyBefore: 'Over the years, we have served ',
      copyMetric: '530+ companies',
      copyAfter: ' across a range of industries.',
      logos: 'Partner companies',
    },
    process: {
      kicker: 'Our approach',
      title: 'How we innovate to find solutions.',
      intro: 'A transparent, collaborative, results-driven way of working.',
      steps: [
        { title: 'Discovery', copy: 'We identify which capabilities to prioritize or create during the production process.' },
        { title: 'Refinement', copy: 'We clarify each item, making the work easier to understand and carry out.' },
        { title: 'Development', copy: 'A focused team works toward a goal that delivers meaningful value on schedule.' },
        { title: 'Review and adapt', copy: 'We review what has been built and decide which adaptations come next.' },
        { title: 'Feedback', copy: 'We listen to the right people to set direction and confirm the outcome meets its goal.' },
      ],
      contact: 'Talk to a specialist',
    },
    solutions: {
      kicker: 'Solutions',
      title: 'Turn your needs into reality.',
      intro: 'Discover how Jetsoft can help your business move forward.',
      descriptions: [
        'Integrated, end-to-end management for your entire business.',
        'Grow your brand’s visibility with digital marketing solutions.',
        'Sell more online with a platform connected to leading marketplaces.',
        'Custom software development: apps, web systems, and innovative solutions.',
        'Invest in your team with training, development, and consulting.',
        'Improve results through process mapping, optimization, and automation.',
      ],
      action: 'Learn about {name}',
    },
    articles: {
      kicker: 'Insights',
      title: 'The latest in technology and business.',
      action: 'Talk to us about this topic',
      items: [
        { date: '05.28.2024', title: 'Is cloud ERP as secure as traditional ERP?', aria: 'Talk to Jetsoft about cloud ERP' },
        { date: '05.22.2024', title: '“Hello, World”: programming’s first message', aria: 'Talk to Jetsoft about programming' },
        { date: '05.22.2024', title: 'The benefits of adopting a low-code tool', aria: 'Talk to Jetsoft about low-code' },
      ],
    },
    footer: {
      brand: 'Jetsoft is a Brazilian company born from the desire to turn dreams into reality.',
      usefulLinks: 'Useful links',
      home: 'Home',
      contactInfo: 'Contact information',
      footerLead: 'We would love to hear about your challenges.',
      footerAction: 'Get in touch to find a solution',
      rights: 'All rights reserved.',
      backToTop: 'Back to top',
    },
    social: { linkedin: 'LinkedIn', instagram: 'Instagram', facebook: 'Facebook' },
    whatsapp: 'Talk to Jetsoft on WhatsApp',
  },
};
